name: globalproxy

services:
  fe:
    image: pigeatgarlic/fe
    restart: unless-stopped
    env_file:
      - ./.env
  globalproxy:
    image: pigeatgarlic/global-proxy:latest
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - /root/pb_data/.autocert_cache:/app/pb_data/.autocert_cache
    command:
      - '-dom'
      - 'official.thinkmay.net'
      - '-dom'
      - 'fe.thinkmay.net'
      - '-dom'
      - 'www.thinkmay.net'
      - '-dom'
      - 'thinkmay.net'
      - '-feport'
      - '443'
