name: supabase
services:
  globalproxy:
    image: pigeatgarlic/global-proxy:latest
    restart: unless-stopped
    # ports:
    #   - 445:445
    volumes:
      - /home/huyhoang/assets/pb_data/.autocert_cache:/app/pb_data/.autoce
      - /home/huyhoang/assets/config.yaml:/app/config.yaml